version: '3'

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:

services:
  db:
    image: postgres:15-alpine
    container_name: postgres
    networks:
      - app-network
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=yobank
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    networks:
      - app-network
    ports:
      - "8080:8080"
    depends_on:
      - db
      - broker
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=123
      - DB_NAME=yobank
      - ACCESS_TOKEN_EXPIRY_HOUR=2
      - REFRESH_TOKEN_EXPIRY_HOUR=168
      - ACCESS_TOKEN_SECRET=access_token_secret
      - REFRESH_TOKEN_SECRET=refresh_token_secret
      - SMTP_HOST=smtp.yandex.ru
      - SMTP_PORT=465
      - SMTP_USERNAME=roflandown@yandex.ru
      - SMTP_PASSWORD=
      - TELEGRAM_BOT_TOKEN=
      - TELEGRAM_WEBAPP_URL=https://t.me/yobankbot?startapp

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend
    networks:
      - app-network
    ports:
      - "80:80"
    depends_on:
      - backend

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    networks:
      - app-network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    networks:
      - app-network
    ports:
      - "9092:9092"
      - "9093:9093"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LISTENERS: PLAINTEXT_INTERNAL://0.0.0.0:29092,PLAINTEXT_C://0.0.0.0:9093,PLAINTEXT_L://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INTERNAL://broker:29092,PLAINTEXT_L://localhost:9092,PLAINTEXT_C://broker:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT_L:PLAINTEXT,PLAINTEXT_C:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    networks:
      - app-network
    depends_on:
      - broker
    ports:
      - "7777:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=broker
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=broker:9093
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
