version: '3'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=yobank
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=123
      - DB_NAME=yobank
      - ACCESS_TOKEN_EXPIRY_HOUR=2
      - REFRESH_TOKEN_EXPIRY_HOUR=168
      - ACCESS_TOKEN_SECRET=access_token_secret
      - REFRESH_TOKEN_SECRET=refresh_token_secret
      - SMTP_HOST=smtp.yandex.ru
      - SMTP_PORT=465
      - SMTP_USERNAME=roflandown@yandex.ru
      - SMTP_PASSWORD=
      - TELEGRAM_BOT_TOKEN=
      - TELEGRAM_WEBAPP_URL=https://t.me/yobankbot?startapp

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
